import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Music Next App",
  description: "Generated by Stuepp",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-l from-indigo-500 to-indigo-800 '>{children}</body>
    </html>
  );
}
//{inter.className}
/*
DB

CREATE TABLE Song (
	SongID INT PRIMARY KEY
	nome varchar(30),
	song varchar(300)
);


*/